### ISSUE TITLE
Librarian can designate an item as being consumable/single-use

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#1007]
As I librarian, I want to be able to flag an item as being consumable/single-use, so that I can classify seeds correctly.

- [ ] checkbox on Edit Item page, something like "single-use"
- [ ] add column table (items table?) to correspond to this
- [ ] add borrow policy for single-use items (row in table)
- [ ] Add a validation to items with this borrow policy that requires a quantity?

**Comment by pjsier** [comment]
Would this need to be on the item table or could something like a `consumable` column be added to the borrow policy and all items attached to the borrow policy follow these rules?

**Comment by jim** [comment]
@pjsier I think the borrow policy is the right place for that. At least that's where I put it in #1016.
