### ISSUE TITLE
Specify GitHub action versions

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#1017]
**Describe the bug**

We are using various GitHub actions in our CI pipeline. Some of them are pointing to the main branches of the respective repo, which means they are a moving target. We recently had [an issue where CI failed](https://github.com/rubyforgood/circulate/runs/5604817196?check_suite_focus=true) because [a bug was introduced in one of the setup actions we use](https://github.com/nanasess/setup-chromedriver/issues/40).

To fix this, let's lock any GitHub actions to specific versions. This all lives in [.github/workflows/ci.yml](https://github.com/rubyforgood/circulate/blob/main/.github/workflows/ci.yml).

**Comment by MrFuku** [comment]
@jim Nice to meet you!
I have created a PR that solves this problem, if you would like to take a look at it?
https://github.com/rubyforgood/circulate/pull/1018

**Comment by jim** [comment]
Fixed by #1018.

Thank you for the contribution!
