### ISSUE TITLE
Member logs in

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#104]
As a member, I want to be able to log in to my account so that I can access member features.

Login should be e-mail and password, and should include normal bells and whistles like error-checking, checkbox to remember the user, etc.

After login, go to the My Loans & Holds screen (see #110 ). Make sure to update the nav as well.

See babywearing repo for code to reuse, see mock-ups for general sense of the thing.

set up database with this issue?
will need to create member accounts with password first

See [Member portal mock-ups](https://drive.google.com/file/d/172gIc-yOgd-yAxbv4_qnVnC0JwMqacXo/view).

**Comment by jim** [comment]
I think the final piece of this is captured in #174, so I'll close this one.
