### ISSUE TITLE
Add verified members to admin dashboard

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#1046]
As a library administrator, fundraising committee member, board member, or similar, I want to be able to easily and quickly see the number of Verified Members, so that I can keep an eye on the impact of the library.

- Add total verified members to the admin dashboard (e.g., https://circulate-staging.herokuapp.com/admin). This could simply go next to "Members" on the dashboard under the third "Total" row, "Verified Members," where underneath is the total verified members.

- On the same dashboard, we could also add the corresponding metrics at the end of the "This Week" row, i.e., "Members Verified," where underneath are the number of members verified this week.

See screenshot for potential placement:
![Screen Shot 2022-04-27 at 8 11 43 PM](https://user-images.githubusercontent.com/7916357/165651736-b303adce-1cba-4c4a-9d5f-4be2ff9d3d59.png)

**Comment by ukulelelesheep** [comment]
I'm on it!
