### ISSUE TITLE
Member views profile/user info

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#105]
As a member, I want to be able to view my user information, so that I can see if it's incorrect or so that I can look up my member information.

What constitutes user info?
editable
- name
- pronouns
- e-mail
- telephone
- zip code
- street address?

not-editable (display only)
- membership status
- membership no.
- membership expiration date

See babywearing repo for code to reuse. 

See bottom of [Member portal mock-ups](https://drive.google.com/file/d/172gIc-yOgd-yAxbv4_qnVnC0JwMqacXo/view).

Related to #106.

**Comment by jim** [comment]
This was closed by #131
