### ISSUE TITLE
Member requests/reserves items

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#108]
As a member, I want to be able to request an item for hold or pick-up without having to fill out a form so that I can get an immediate response to my request.

Next iteration on current hold requests (https://ctl-staging.herokuapp.com/holds, and see credentials at https://docs.google.com/document/d/1LOyhJ5MD8EMKQR14B93xrTy_SP7IuB7i5QhN9ARgEAo/edit#)-- should be a button next to the item in inventory rather than a separate interface, and should be available only after logging in.

**Comment by italomatos** [comment]
@rkim00 Hey, I tried to access staging environment with admin credentials in the file on Google Drive ( like you describe in description), but I can't.

**Comment by rkim00** [comment]
Hi @italomatos , I think this is an old issue that hasn't been cleaned up yet. That's why it's not labeled Hacktoberfest or Help Wanted. Sorry for the confusion—I'll close this. Are you looking for more issues? More coming soon! If you have any particular types of issues you're looking for, send me a note in our Slack and I can look for some.

**Comment by rkim00** [comment]
I think this issue was accomplished by Scheduler changes. I see a "Place a hold" button on item pages now.
