### ISSUE TITLE
Member can request renewal for B & C tools

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#123]
As a member, I want to be able to request to renew "B" & "C" category tools right from the app, so that I don't have to write an e-mail to do so.

On the My Loans page, next to B & C category tools that are checked-out, Members should get a "request renewal" link (or button) if
- the length of time between today and the due date is < the standard loan period for the item AND
- there are no pending holds for that item.

After clicking on this link:
- renewal request is stored in the database (model/table probably doesn't exist yet) as pending
- Link should change to plain text that reads, "Renewal requested. We'll e-mail you an update."

Renewal request should be associated with at least this information:
- date of request (probably time as well)
- member making the request
- loan requested to be renewed

See mock-ups:
https://drive.google.com/file/d/1sbf62tG2x7nUCHX5DN8_neipsGQqtdqs/view

See admin Member page view for related renewal code, e.g., https://ctl-staging.herokuapp.com/admin/members/399.

Also see #173 for related functionality.

Note that this story is related to a number of other stories (#307, #305, #306, #346) that should probably be launched at the same time. Therefore, may want to disable/hide the link in Production until the other stories are merged and tested.

For reference, A tools renewal: #151, #344

**Comment by pjsier** [comment]
I'm interested in taking this!

**Comment by jim** [comment]
This is done!
