### ISSUE TITLE
add item # to displays of loans in admin screens

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#148]
As an librarian/admin, I want to be able to see item #s next to loans, so that I can see more details on the specific loan, and get a sense of what categories of tools are loaned out.

For all three views (checked out, overdue, returned), add two columns, one for category (by letter) and one for item # next to loans.

![loans pages annotated](https://user-images.githubusercontent.com/7916357/92996475-d8c39b80-f4d9-11ea-90d9-139f84999357.png)

**Comment by cjilbert504** [comment]
Hello all, I would like to hop on this issue if it's still available.

**Comment by rkim00** [comment]
@cjilbert504 , just saw this, sorry for the delay. Feel free to just grab issues -- you've got permissions to do so, I think. Nevertheless, I've assigned to you for now. Let me know if you have any questions! And I watch the Slack channel much more than these comments, so you'll get faster responses there.
