### ISSUE TITLE
Add "power source" field to item.

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#152]
We want to track what is powering items (if they are powered). To do this, we'd like to add a `power_source` column to the `items` table.

Items don't have to have a value (a blank value will be interpreted as that item not being powered). For those items that do have a value for `power_source`, it can be one of: solar, gas, air, electric (corded), or electric (battery).

This value should be editable for admins on the item edit form, and displayed on that item's page both in the admin view and the public inventory.

**Comment by swanson** [comment]
Any preferences on how to store the `power_source`? Will admins want to add other options down the line?

I think there are three options:

- Store `power_source` values as a string in the database
- Use an enum
- Add a `power_sources` table and use an association

**Comment by swanson** [comment]
I'm going to work on this issue. It looks like the convention is to use a database enum, so I will proceed down that path.

**Comment by johnksawers** [comment]
Might we want to specify 120v vs 220v as well?

**Comment by jim** [comment]
@johnksawers That's a good point. CTL doesn't have anything that is 220, but I imagine it could come up. We could break `electric (corded)` into `electric (corded, 120v)` and `electric (corded, 220v)`.

**Comment by jim** [comment]
@swanson Database enum would be great!

If you want to be also be able to leverage the ActiveRecord enums as well, you can use this approach: https://blog.testdouble.com/posts/2019-06-03-enumerate-your-enums/ The main benefit here is probably that it makes rendering the form slightly easier, and also lets the database value not include parenthesis, spaces, or other special characters.

**Comment by jim** [comment]
@swanson I see you already made a PR. Thanks!
