### ISSUE TITLE
Librarian: Add number of active loans and holds to member index

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#154]
The admin members index shows a list of all members and some of the information associated with their account.

Add two columns to this listing that shows how many items the member is currently borrowing and how many holds they have. The new columns can be added to the right side of the table.

If either of the values is 0, display a `-` for that value so that they page is easier to scan. Otherwise, show the value.

**Comment by matisnape** [comment]
Hi, I would like to take this one :)

**Comment by jim** [comment]
@matisnape That sounds great! I'll assign it to you.

**Comment by matisnape** [comment]
@jim are you joining Hacktoberfest with the new rules? It's now opt-in for open source projects https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by jim** [comment]
@matisnape Thanks for asking! I added the `hacktoberfest` label to the repo a little bit ago, so I think we're all set.

**Comment by matisnape** [comment]
Hey folks, I created a PR. Question: have you thought about using a formatter for .scss files or lack of it is deliberate? (My editor did a lot of changes in the file i touched on save, that's why I'm asking :))
