### ISSUE TITLE
Librarian: Add notes to members (similar to those that are on items)

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#155]
Items can have notes attached to them so that library staff can add information to that item for other staff to see. Examples might be that someone reported an issue with the tool or that it was recently sharpened.

We'd like to add a similar ability to member accounts so that we can track things like someone returning tools in a dirty state, that someone bought a new blade for a tool, etc.

[Admin::NotesController](https://github.com/rubyforgood/circulate/blob/development/app/controllers/admin/notes_controller.rb) was written to make adding notes to additional model possible, but some minor modifications may be needed.

UI-wide, we'd like to display any notes on a member in the left column of the member profile page, underneath the "Member Details" section.

**Comment by chaserx** [comment]
Hi @jim I'm looking into this and need some clarification. 

I found a `notes` text field when an admin is editing a member. 

<img width="1124" alt="Screen Shot 2020-10-10 at 12 39 20 PM" src="https://user-images.githubusercontent.com/7292/95660441-ea5a8c00-0af5-11eb-967a-ef13af9bb623.png">

Is that note on member edit form also viewable to the member? 
I'm wondering if we can continue to use these member notes and just expose those notes in the side bar? Or if notes could be created by n-number of librarians and the author relationship is an important feature here?

**Comment by chaserx** [comment]
Now that I look at this more closely, I see how notes on items works. I think I've answered my previous questions. I can probably take a crack at this one. I'll assign myself.

**Comment by rkim00** [comment]
Great, thanks. Let us know if you have any other questions. FYI if you haven't discovered already, member-editable fields can be seen on a page like https://circulate-staging.herokuapp.com/member_profile/edit .

**Comment by chaserx** [comment]
Hi 👋 I've made a lot of progress here, but have been swamped at work lately. My plan is to finish this up this weekend (2020-10-25).
