### ISSUE TITLE
Librarian: Add "renew all" button to admin view member page that renews all borrowed items.

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#156]
Often a librarian renews all of the items for a member. We'd like to add a "Renew All" button to the admin member page so that staff can click one button to accomplish this instead of having to click renew on each item that is currently checked out. We've had some issues where one item gets missed, and hopefully having an easy way to renew all items will make this less common.

Renewing items in this way should have the same effect as if a staff member had clicked "Renew" manually on each item: a single item renewal should be able to be undone, etc.

This button can be places above the list of checked out items on the "Current Loans" tab of the admin member page. If you have an idea for a better place to put it, please go ahead and do so!

**Comment by chaserx** [comment]
I'm going to assign myself here. I think I can contribute to this issue.

**Comment by rkim00** [comment]
Thanks, it's yours! Also inviting you to our repo, in case you just want to self-assign yourself to issues.
