### ISSUE TITLE
Make member type in old password to edit new password.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#167]
As a member, I want to be required to enter my current/old password when I edit my password, so that someone can't maliciously change my password without my knowledge if I leave my computer open after logging in.

**Comment by jim** [comment]
@amygurski Have you had a chance to work on this? We have other folks interested in giving it a shot if you won't have time in the near future. Cheers!

**Comment by amygurski** [comment]
@jim thanks for the reminder. let me see if i can do it this afternoon. if not, i'll let you know and take my name off it.
