### ISSUE TITLE
Fix test errors on main branch ("main")

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#172]
JavaScript errors on test member can edit profile
seems to be conflicting with nav bar changes. Some of what people said in the Slack chat:

> Is this an issue? I think its from the pull request I merged in recently https://app.circleci.com/pipelines/github/rubyforgood/circulate/312/workflows/91743758-ce77-4caa-bbbc-3a43c13aa05f/jobs/1611

> I just started a run again. We had 1 test fail in CI that passed locally and reran CI and it passed.

> Different failures :lol: https://app.circleci.com/pipelines/github/rubyforgood/circulate/312/workflows/05983c6e-dbf6-42b4-bf38-6e3eaea49e8e/jobs/1616

> When there's the same generic error sent for a rotating list of different test cases, that smells like a general setup problem. > Like, probably all JS tests are affected.

> It might consistently fail the CI test *suite*, but the test that appears as failing is random because test order is random. *I think*.

----
2 Nov 2020 update: some of the tests failing recently on CircleCI (in `test_system`):

> test_member_sees_validation_errors_on_update_failure - MemberProfileTest
> test/system/member_profile_test.rb
> Unable to find css ".primary-btn"
> test/system/member_profile_test.rb:35:in `block in <class:MemberProfileTest>'

> test_member_can_edit_profile - MemberProfileTest
> test/system/member_profile_test.rb
> Unable to find css ".primary-btn"
> test/system/member_profile_test.rb:20:in `block in <class:MemberProfileTest>'

**Comment by RachelWyatt** [comment]
Hi! I'm new to the project but would love to help out here. Is this still open for the taking?

**Comment by rkim00** [comment]
Yes, sure, although I'm not sure about the latest on this problem; I think we've been seeing similar errors pop up and there may be some more collected wisdom on it.

I assigned to you, but you may want to also post to our #circulate channel in the Ruby for Good Slack (https://rubyforgood.herokuapp.com/) and see if there are additional thoughts, particularly if you get blocked on understanding or reproducing the problem. Thanks much!

**Comment by rkim00** [comment]
Also, this issue could definitely be written up more clearly and with more detail. Let me know if there's too little to go on and I can do my best to add more information.

**Comment by jim** [comment]
These have mostly settled down and we've had a string of green builds.
