### ISSUE TITLE
On login, redirect Members to My Loans page and Admins to Admin page

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#174]
Currently logging in redirects both Members and Admin/staff to the "app homepage" (https://circulate-staging.herokuapp.com/).

Logging in should redirect Members without staff/admin privileges to the My Loans page (https://circulate-staging.herokuapp.com/member/loans), while it should redirect staff or admin (who are also likely Members) to the admin page (https://circulate-staging.herokuapp.com/admin).

See also #216 .

**Comment by preethinarayan** [comment]
@rkim00 could I pick this up?

**Comment by rkim00** [comment]
You got it! Thanks! Let me know if you have any questions.
