### ISSUE TITLE
Member can schedule a return time

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#178]
As a member, I want to be able to schedule a time to return my items through the app, so that I can return my checked-out items safely without having to send lots of e-mails to make an appointment.

- Should only be able to return an item once it's been "Checked Out"
- Should tie back into "Schedule An Appointment" page that we worked on here:
https://github.com/rubyforgood/circulate/issues/204
- Should be able to schedule returns and pick ups in the same appointment

**Comment by rafbgarcia** [comment]
I believe this issue was also done on https://github.com/rubyforgood/circulate/pull/230, is that correct @gregblake?

**Comment by gregblake** [comment]
@rafbgarcia Yes, we did end up finishing this one on https://github.com/rubyforgood/circulate/pull/230.

**Comment by gregblake** [comment]
@sboligitz @rkim00 I just closed this issue, since it was done on https://github.com/rubyforgood/circulate/pull/230. But if there's anything we missed on this issue, feel free to reopen this one.
