### ISSUE TITLE
UX: make taxonomy/labels more readable

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#184]
On inventory pages, make the taxonomy/labels more readable. For example:
- distinguish more clearly between levels of hierarchy
- fix the gaps between certain categories (e.g., Assistive Devices & Automotive, Metalwork and Personal Protective Equipment, etc.)

Possibly could use some collapse and expand features.

https://circulate-staging.herokuapp.com/items

**Comment by metamoni** [comment]
Hi 👋 

I can take this one!

**Comment by rkim00** [comment]
Oh great! Let me know if you have any questions—this one is a bit hairy! Thank you!

**Comment by jim** [comment]
This was closed by #299
