### ISSUE TITLE
Holds should automatically cancel if not Scheduled within 14 days.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#195]
As a Librarian, I want Member's Holds to expire if not scheduled for pick-up within 14 days so that Members don't hold up other Members in the queue from checking out desirable tools.

Currently, the My Loans & Holds screen tells Members to pick up their tools by a certain date, but we don't do anything if they don't pick this up in time. This means that a Member could potentially keep an item on hold forever, keeping others from being able to check out the item.

We should instead expire out a hold after 14 days. The clock should start running from when (a) a member is first in line to borrow a tool and (b) the tool has been returned. I'm not sure how the current date is generated; probably information on this in #343 .

If the item has not been checked out by the member after 14 days, remove the hold. From a UX standpoint, simplest is just to remove the item from My Holds... open to alternate ideas. (E.g., maybe we display the Hold as expired for three days?)

Some cases to consider:
- Member checks out the item within 14 days: the hold should be removed at time of check-out already.
- Member doesn't schedule an appointment: the hold should expire after 14 days, and the next person in line should be allowed to check things out.
- A librarian checks out the item to a different member after the original Member's 14-day clock has started: hopefully this never happens, but I _think_ the system will put the original Member back on hold. Not sure... worth investigating.
- Member schedules their appointment for a date after the 14 days. This is an edge case we aren't catching yet. I think by default the Member will lose their hold before their appointment, which is too bad. I've written a separate issue to catch this case (#375  ), which is an error-check on scheduling an appointment that blocks the member from making the appointment outside the hold window.

May be affected by Member cancelling appointment (#354) and not allowing scheduling an appointment until item is returned (#343 )

**Comment by chaserx** [comment]
Hi @rkim00 I'm new to this project, but I think I could contribute to this issue. Could you clarify what `Reservations` refers to here? I'm looking through the schema and it looks like `Holds` is the closest analogous model. Do I have that correct?

**Comment by chaserx** [comment]
@rkim00 if my previous assumptions are correct. Here's a stubbed out development plan not including tests. 


- Add a new timestamp column on `hold_request` table to record the cancellation of the request. 
- Update the status enum list to include `cancelled`
- Add a rake task to lib/tasks that can be invoked by cron via the Heroku scheduler. This task will check for   `hold_requests` in batches where `status` is `new` and `created_at` > 14 days from the current date. Timezones are tricky. We'll assume that timestamps and server time are both in UTC. Then update all hold_requests with the current time for cancellation and set cancelled status. Send an email to that same set of users stating as such. 
- Create a new mailer view with the information that their request was cancelled due to inaction. Perhaps with a prompt to re-request, renew that hold.

**Comment by rkim00** [comment]
Hi, sorry I didn't see this earlier and respond. I moved this to our backlog because I wasn't sure if recent changes had incorporated this already. I think not, but I'm not sure, so apologies if as you look into this you find it's already done.

Reservations was an early term we were using for this; I think the schema term should be holds, not hold_requests.

As for your plan, I'm not enough of a back-end developer to know whether it makes sense, but I'll tag @jim on this. Also FYI, if you get blocked waiting for an answer, there's a number of folks who can answer questions on this sort of stuff in the Ruby for Good Slack, in the #circulate channel. You can join at https://rubyforgood.herokuapp.com/ . Thanks so much for contributing!

**Comment by rkim00** [comment]
Oh, a little more info: hold_requests is a `hold` + an appointment time, but I believe `hold_requests` is deprecated in favor of `appointment` and `appointment_holds`.

**Comment by rkim00** [comment]
@jim or @johnksawers , are you able to give any feedback on Chase's plan above? Thanks!

**Comment by jim** [comment]
Hi @chaserx ! Thanks for your thoughts on this one.

I think your rake task and email steps make sense. The first couple would need to be modified to use the Appointment models, though. @rkim00 is correct in that `HoldRequest` is deprecated- it was part of an earlier work stream that we removed when we added appointments.

* We create a `Hold` to represent that a member wants to borrow an item.
* There are `Appointment`s that represent a member coming in to the library, and `AppointmentHold`s and `AppointmentLoan`s to represent something that will be returned.

I think we probably need to add the concept of `expired` to `Hold`, using the following rules:

* An active hold expires 14 days after it is created

Holds that are picked up should be marked as `ended`, and so this won't apply to them.

We will also need some logic around what happens to an appointment if all of its holds expire, but I think that can be another story. WDYT @rkim00?

**Comment by rkim00** [comment]
Hi @jim and @chaserx . I think we actually need to flesh out a little more when the clock starts running.

Presumably I should be able to put a hold on an item far in advance, > 14 days. The 14-day clock should start running when (1) I am first in line in the hold queue, and (2) the item has been returned to the library.

Then I think I should have 14 days from then to _schedule_ my hold. After that hold is scheduled for pick-up, my hold shouldn't expire; the clock is paused.

The edge case is if the user or administrator cancels the appointment; should the clock restart at 14 days? I think easiest and simplest is that it does, although a user could game things by cancelling their appointment and then rescheduling.

And so I wasn't conceiving of a scenario where holds expire out of an appointment, but where the appointment prevents the hold from expiring.

@jim how does that sound, and am I understanding you correctly? It's possible I'm not understanding what an "active" hold is.

And perhaps 14 days is too generous, but that's the overall framework. (Obviously the 14 days should be in a database somewhere... perhaps to be set differently for different lending policies—@jim, where would that be?)

**Comment by jim** [comment]
You're right, we need to track the time when the person moves to the front of the line as when the 14 days starts and not when the hold is created.

When an appointment is cancelled, I think the hold returns to a state where it can expire, but I don't think we should restart the 14 day clock. Folks will sometimes cancel and pick a new appointment, and keeping that with 14 days is probably best. I think this is simpler, too, since it relies on the same original time that the clock was started. If we wanted to start a new 14 day period, it might be simpler internally to just create a new hold so that the rules are simpler.

**Comment by rkim00** [comment]
FYI @chaserx , @jim and I are discussing how to proceed with this—stay tuned! Your opinions welcome, of course.

**Comment by rkim00** [comment]
@chaserx , @jim and I have discussed and I think we've figured it out! We're basically going with Jim's idea—I've updated the original description, and we should be good to go if you still want to work on this. Let me know if you have any questions.
