### ISSUE TITLE
Pull out and combine link partials on nav bar for Members & Admins so that we aren't maintaining links in two places for desktop vs. mobile.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#234]
#236 set up a set of links that display when the screen is narrow, for mobile users. These links are duplicative of the links that display of the links in the main navbar.

Abstract out the link text and URL (and whatever else makes sense) for each of these navbars so that links only need to be updated in one place.

**Comment by italomatos** [comment]
What are thinking about this card, @rkim00 ?

**Comment by rkim00** [comment]
@italomatos added some more detail to the description. Does that help? Let me know if you have any other questions.

**Comment by italomatos** [comment]
> @italomatos added some more detail to the description. Does that help? Let me know if you have any other questions.

Thank fou details. I did, waiting PR review. Good idea to do a partial view 👏🏻👏🏻
