### ISSUE TITLE
Librarian Appointment Page - Edit Date and Time

### ISSUE THREAD

**Issue by sboligitz** [rubyforgood/circulate#237]
As an librarian I should be able to edit the date and time of a scheduled appointment.

On pages like https://circulate-staging.herokuapp.com/admin/appointments/5 , should be able to edit the date and/or time.

Best way to do this is probably to add a small "edit" button/link next to the date. 

Easiest thing to do after is probably to take the user to a separate edit screen, with a pulldown to select a new date, and "confirm" and "cancel" buttons.

Alternately, we could do something like: clicking on the button would replace the date with a pull-down that fills in the existing date & time with other date & time selections, and that has "confirm" and "cancel" buttons underneath it.

In either case
- confirm would change the date & time and update the database
- cancel would take the user back to the original screen with no changes

See pages like https://circulate-staging.herokuapp.com/account/appointments/new for implementation of date & time pull-down.

Spun off from #207 . Related to Remove Item (#260 ) and Add Item (#259 ).

**Comment by rkim00** [comment]
Hey @terryfinn , are you still wanting to work on this issue? We might have others that are willing to pick it up if you don't have time for it. Just let us know.
