### ISSUE TITLE
Fix item link on My Loans so that it goes to the item page.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#253]
Currently link to Items on "My Loans" page (https://circulate-staging.herokuapp.com/) under "My Loans & Holds" doesn't go anywhere. Link this to the corresponding item page, e.g., https://circulate-staging.herokuapp.com/items/67

**Comment by Rajdeepc** [comment]
@rkim00 There is no "My Loans & Holds" section in the homepage https://circulate-staging.herokuapp.com/
Please be more specific.
