### ISSUE TITLE
Figure out why scheduling an appointment doesn't seem to work on Staging.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#258]
Currently when a logged-in member schedules an appointment on an item in Staging (https://circulate-staging.herokuapp.com/), the appointment doesn't seem to be created and the member gets redirected to a 404-ish page. Would be great to (1) diagnose and (2) fix.

maybe be related to #255

**Comment by jim** [comment]
@rkim00 @terryfinn We had hit the database row limit on staging, which was breaking things in a lot of weird ways. That problem is resolved now, so we should test to see if this issue is still valid.

**Comment by rkim00** [comment]
I think this is fixed now. Thanks!
