### ISSUE TITLE
Admin Appointment Page - Add Item for check-out

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#259]
As an librarian I should be able to add an item to a scheduled appointment for check out.

On pages like https://circulate-staging.herokuapp.com/admin/appointments/1 , should be able to add an item to the Scheduled Appointment for eventual check out.

Spun off from #207 . Related to Edit Date (#237 ) and Remove Item (#260 ).

**Comment by fosterv2** [comment]
From what I can see, a user can already add an item to a scheduled appointment for check-out, but there isn't a way to add an item for check-in. Should I be adding a way to add items for check-in to solve this issue, or is there something else I'm missing?

**Comment by rkim00** [comment]
Yes, sorry about that. There was some miscommunication about which issues were open.

If you'd like to work on code to add items for check-in, that would be great. I'll write up a separate issue for that; let me know if you want me to assign you to that.

**Comment by rkim00** [comment]
The "Add item for check-in" is written up as #283 now. Closing this issue.
