### ISSUE TITLE
Admin Appointment Page - remove Item for check-out

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#260]
As an librarian I should be able to remove an item from a scheduled appointment for check out.

On pages like https://circulate-staging.herokuapp.com/admin/appointments/1 , should be able to remove an item from the Scheduled Appointment for eventual check out.

Spun off from #207 . Related to Edit Date (#237 ) and Add Item (#259 ).

**Comment by avinashupadhya99** [comment]
Hey, I can work on this. Please assign this to me.

**Comment by rkim00** [comment]
@avinashupadhya99 , I've assigned to you, but have we given you enough context to work on this? Mock-ups are here: https://drive.google.com/file/d/1fK-AI8Cf5xe6-Bf5nIE1DiZ_UWDw6gQK/view , and there's more detail in #207 . Also, you can join our Slack group at https://rubyforgood.herokuapp.com/ and ask questions in the #circulate channel. Thanks!

**Comment by rkim00** [comment]
This issue now appears to have been fixed.
