### ISSUE TITLE
Add hacktoberfest to repository topics

### ISSUE THREAD

**Issue by pineappledreams** [rubyforgood/circulate#262]
Hey, uh happy October everybody.

Hacktoberfest has new rule that the repo needs to have `hacktoberfest` as a tag on the repo to count, so it would be great if it would be added. Personally for me, as Ruby on Rails is very much up my alley.

Thanks so much!

**Comment by jim** [comment]
@pineappledreams Thanks for bring this to our attention! I added the tag to the circulate repo.
