### ISSUE TITLE
Membership columns are named incorrectly

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#263]
`memberships.started_on` and `memberships.ended_on` store timestamps but are named using `_on` which indicates that they should be dates. Rename these columns to `ended_at` and `started_at` using a database migration to align their names with the values they store.

**Comment by jim** [comment]
This is dupe of #264

**Comment by verma-pulkit** [comment]
Hey Jim,I would like to take this up. And try my best.

**Comment by jim** [comment]
@verma-pulkit Sounds great. I'll close the other one then and assign this one to you.

**Comment by dannyflatiron** [comment]
The migration would only change the column names, not the datatype?

**Comment by dannyflatiron** [comment]
Hello, is this issue still available?

**Comment by akp2603** [comment]
Hey @jim is this issue still available, would love to fix this.

**Comment by rkim00** [comment]
@verma-pulkit are you still working on this issue? No worries if you still are, but if not, some other people have been asking to take it.

**Comment by efgalvao** [comment]
Hi, I'm learning ruby and would like to try to fix this.

**Comment by verma-pulkit** [comment]
@rkim00  I am sorry, I got stuck in college work. Sorry would not be able to work on this.

**Comment by rkim00** [comment]
Thanks for the update @verma-pulkit .

@dannyflatiron @akp2603 @efgalvao would any of you like to take this issue?

**Comment by akp2603** [comment]
I can help with this. You can go ahead and assign it to me.

**Comment by rkim00** [comment]
Thanks! Assigned!

**Comment by leahriffell** [comment]
Hi @akp2603! Are you still working on this? If not, I can pick it up.

**Comment by akp2603** [comment]
@leahriffell sure, you can pick it up.

**Comment by jim** [comment]
@leahriffell If you still want this one, it's all yours 😄
