### ISSUE TITLE
Replace use of fixtures with factories

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#266]
This project used the default Rails factories early in its life, and once [FactoryBot](https://github.com/thoughtbot/factory_bot) was introduced all new tests have been written to use that approach instead. Some of the older tests have been updated to use factories instead of fixtures, but there are some that are still using fixtures.

We need to remove all test fixtures from the project and update any tests that still use them to leverage factories.

**Comment by italomatos** [comment]
Can I do it?

**Comment by rkim00** [comment]
Sure, give it a shot! Feel free to join our Slack group at https://rubyforgood.herokuapp.com/ ; you can ask questions in the #circulate channel. Welcome!

**Comment by italomatos** [comment]
@rkim00 this was finished 🚀
