### ISSUE TITLE
Member view: rearrange links on nav bar

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#273]
Links on nav bar on pages like https://circulate-staging.herokuapp.com/member/loans display like this for a logged-in member who is also a Librarian when on desktop / wide screen:

![nav bar](https://user-images.githubusercontent.com/7916357/95048929-c0006d00-06b6-11eb-9068-369c13e3c8ba.png)

with the order, L to R:
- logo
- View Inventory
- Admin Dashboard
- search box

Rearrange this order so it's more consistent with the mobile / narrow-screen view of this page, that is:
- logo
- search box
- pipe ("|")
- View Inventory
- Become a Member (if not logged in)
- Admin Dashboard

**Comment by ariane-h** [comment]
Hello 👋 I've had a go at this here #279

**Comment by rkim00** [comment]
Thanks! Looks good, but I'm unable to review on a box at the moment. Hopefully one of our tech leads can review this in the next 24 hours or so.
