### ISSUE TITLE
Member view: rearrange links and fix text in Member pulldown in nav bar

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#274]
When a Member is logged in, links in the right pull-down should be in a different order (e.g., on https://circulate-staging.herokuapp.com/appointments#), and some of the text should be different.

![Member pulldown](https://user-images.githubusercontent.com/7916357/95049760-64cf7a00-06b8-11eb-9a4b-2ff4cffd7bb7.png)

The current order reads:
- My Appointments
- My Loans / My Holds
- Schedule a Pick Up
- View Loan History
- Account Settings
- Logout

Change the order to the following, and change "My Loans / My Holds" to "My Loans & Holds" and "Schedule a Pick Up" to "Schedule an Appointment":

- My Loans & Holds
- Schedule an Appointment
- My Appointments
- View Loan History
- Account Settings
- Logout

**Comment by dannyflatiron** [comment]
Hello, can I take this?
