### ISSUE TITLE
Update Member links in mobile version of nav bar.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#275]
Mobile links (links & nav that display when the screen is narrow), set up in https://github.com/rubyforgood/circulate/pull/236 , are displaying member links that aren't in sync with the wider-screen version.

Make match #274.

**Comment by Finbob12** [comment]
Hi, Can I take this one?

**Comment by rkim00** [comment]
Sure, assigned to you. I didn't give much context -- let me know if you have any questions.

**Comment by Finbob12** [comment]
Hey thanks, What file/files in particular need adjusting? Sorry fairly new to Rails and don't want to cause a mess

**Comment by rkim00** [comment]
I'm not sure I know any better than you do. But let's see if I can find relevant pull request that set up the links... check out this PR: https://github.com/rubyforgood/circulate/pull/236

**Comment by Finbob12** [comment]
Cool thanks, that helps!

**Comment by rkim00** [comment]
Added a little detail up top too.
