### ISSUE TITLE
Member: Do error-checking on form and give error messages for Schedule an Appointment

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#276]
Currently on pages like https://circulate-staging.herokuapp.com/appointments/new?
1. members can schedule an appointment without selecting any items, and
2. member can submit without selecting a date, which gives a 404-like page.

These are both undesirable. To fix this:

For (1), check the form to make sure at least one item is selected before submitting. If no item is selected, display an error message, "Please select an item to pick-up or return for your appointment."

For (2), check the form to make sure a date and time is selected from the pulldown. If no date is selected, display an error message, "Please select a date and time for this appointment."

There may be other error messages we haven't thought of that should be incorporated as well. Feel free to catch those cases and create error messages for them as well.

**Comment by renugasaraswathy** [comment]
Hi @rkim00, Could you assign this issue to me? Thanks

**Comment by rkim00** [comment]
Assigned, thanks! Let me know if you have any questions.

**Comment by dannyflatiron** [comment]
Hello, I've been working on this and I would like to ask a question just to see if I can get a better understanding. I am running into a NoMethodError for `time_range_string` on this line `<%= select("appointment", "time_range_string", grouped_options_for_select(OpenDays.next_slots_for_select(weeks: 2)), { include_blank: '-- Select a Date --' }, class: "form-select") %>`. When I look in pry I see that `time_range_string` is present in `appointment_params` and set to an empty string value as per the edge case. So I am a little confused as to why I am encountering this NoMethodError for `time_range_string`. I am a beginner, by the way, looking to make my first few open-source contributions :)

**Comment by rkim00** [comment]
Hi Danny. I'm not a back-end engineer at all, so I can't help with your question directly... but if you join the Ruby For Good Slack (https://rubyforgood.herokuapp.com/), and go to our #circulate channel, people will be happy to help answer your question.

**Comment by rkim00** [comment]
However,  you should note that @renugasaraswathy has been working on this and is assigned to this issue. So while you might continue investigating it for your own benefit, we should probably wait for @renugasaraswathy 's pull request.

**Comment by rkim00** [comment]
For some reason these changes aren't showing up in staging.

**Comment by rkim00** [comment]
Now seems to be working in staging.
