### ISSUE TITLE
Fix headings on My Loans & Holds page

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#277]
On this page (https://circulate-staging.herokuapp.com/member/loans):

"Checked-out items" is displaying too small, while "Holds" is displaying too large. They should be the same size, probably something like what displays for the dates on the My Appointments page (https://circulate-staging.herokuapp.com/appointments).

I think "Checked-out items" is an h3 tag, while "Holds" is an h1 tag. Making these both h2 and both the "title_bold" class should get you halfway there.

**Comment by italomatos** [comment]
Can I do it?

**Comment by rkim00** [comment]
@italomatos , it looks like someone else submitted a pull request for this already. :/ I think you're a member of our repo now; feel free to assign yourself to issues that you want to work on!

**Comment by italomatos** [comment]
@rkim00 thanks! 🚀
