### ISSUE TITLE
Member My Loans & Holds -- handle no holds more gracefully.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#288]
When a member has no holds, currently the column headers appears with no holds underneath:
![my_loans](https://user-images.githubusercontent.com/7916357/95261424-6011df80-07f8-11eb-9c24-f572b55862c9.png)

This is a little confusing; it looks like things are broken without a message that the user has no holds.

Instead of displaying nothing under the column headers when there are no holds, remove the column headers and display a message like, "You have no items on hold" below the Holds header. If removing the column headers seems hard or a bad idea for some reason, display this message below the column headers.

**Comment by italomatos** [comment]
I can do it :) 🚀
