### ISSUE TITLE
Member Account Settings: display all editable fields

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#296]
As a Member, I want to see all of my editable Account Settings so that I can read them and know what they are without having to click to edit. 

Currently our Account Settings page (https://circulate-staging.herokuapp.com/items#) 
![account_settings](https://user-images.githubusercontent.com/7916357/95594950-97aba200-0a19-11eb-9757-2232ce1ba27b.png)

displays only a subset of the fields that are available to edit when you click "Edit Member Profile" (https://circulate-staging.herokuapp.com/member_profile/edit).
![edit account settings](https://user-images.githubusercontent.com/7916357/95594963-9c705600-0a19-11eb-8a81-b61653cef64a.png)

We should display all of the information that is available to edit (except for password!), with both category and value.

Specifically, show the user the following fields with values on the Account Settings page
- What kind of tools are you interested in borrowing, today or sometime the future?
- Loan Reminders
- Subscribe to our Newsletter
- Want to help us out?

These can appear below the address information, so that it's roughly in the same place as on the Edit Member Profile page.

"What kind of tools..." can be rendered as the heading with whatever user-entered information below that.

The other categories, which have checkbox selections on the Edit Member Profile page, could be rendered a number of different ways. Probably the easiest way is to reproduce the checkbox + label, regardless if checked or unchecked, but disable it, but other options might involved reproducing the sentences associated with the checkbox as bulletpoints, or rewriting the text for the NOT case (e.g., "Do NOT send me loan reminders via email"). Open to ideas.

**Comment by rkim00** [comment]
Hey @dannyflatiron , are you still interested in working on this issue? If so, no problem. If not, let me know so I can make it available for someone else.

**Comment by dannyflatiron** [comment]
@rkim00 yes, I just need a bit more time

**Comment by jim** [comment]
@dannyflatiron Checking on this one- are you still working on it?

**Comment by dannyflatiron** [comment]
@jim I cannot finish this at the moment. Please unassign me.

**Comment by rkim00** [comment]
Hey @dannyflatiron , thanks for the update. I've un-assigned you.

**Comment by jim** [comment]
Fixed by #436
