### ISSUE TITLE
Helvetica not found in Docker container

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#304]
When running tests using `docker-compose`, the font `helvetica` is not found:

```
$ docker-compose exec web rails test
I, [2020-10-13T04:46:47.641489 #263]  INFO -- Mjml: Using mjml binary at /usr/src/app/node_modules/.bin/mjml
Run options: --seed 51890

# Running:

......................................................................................convert: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1396.
convert: non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4473.
....S.S........................................................................................................................
[Minitest::CI] Generating test report in JUnit XML format...


Finished in 7.956068s, 26.7720 runs/s, 79.6876 assertions/s.
213 runs, 634 assertions, 0 failures, 0 errors, 2 skips
```

On Ubuntu a package needed to be installed to provide this font. Our Docker container uses Alpine Linux, so things might be different there.

**Comment by avinashupadhya99** [comment]
Hey! I am working on this issue. I am trying to find the right package to add.

**Comment by amygurski** [comment]
I sadly spent 3 hours trying to figure this out this evening 🔍 . I really wanted it to be `ghostscript` - that seemed to be the most promising - so for reference adding that to the Dockerfile alone didn't yield anything. Also, in case it helps whomever picks this up, be sure to add `--no-cache` to the `docker build` command when testing Dockerfile changes.

**Comment by m8051** [comment]
Hi @jim, I was able to reproduce the bug **Helvetica not found in Docker container** and update the Dockerfile with a [workaround](https://github.com/rubyforgood/circulate/pull/336) that uses the [Microsoft Fonts](https://packages.debian.org/sid/ttf-mscorefonts-installer) that has a commissioned copy of Helvetica (aka Arial).

Hope that helps.
