### ISSUE TITLE
Librarian/staff can approve renewal requests for B&C tools

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#306]
This story probably comes after #123 and possibly #307  .

As a Librarian, I want to be able to approve renewal requests for B&C tools so that I can allow members to renew their tools without having to come into the library.

See mock-ups (https://drive.google.com/file/d/1sbf62tG2x7nUCHX5DN8_neipsGQqtdqs/view?usp=sharing , bottom of page).

When a Librarian clicks "renew" next to an item, the following things should happen:
- the item is renewed. See functionality on pages like (https://circulate-staging.herokuapp.com/admin/members/1)
- on the View Renewal Requests page (#307 ), as in mock-up, Status should change to "renewed due [date]" and "renew | reject" links should disappear
- on the Member My Loans & Holds page (https://circulate-staging.herokuapp.com/account), as in mock-up, the loan should have a new Due Date and a Status of "checked-out"

The member should also get a "Today's Loan Summary" e-mail like this one (https://circulate-staging.herokuapp.com/rails/mailers/member_mailer/items_on_hold) at the end of the day, with the renewal of the item indicated with a new due date. I believe the text can stay the same for now. This e-mail functionality probably already exists and may work as intended without any changes.

**Comment by pjsier** [comment]
I'm interested taking this one on, potentially at the same time as #305 if that's alright because they seem pretty close
