### ISSUE TITLE
Librarian Appointments View: make UI clearer for adding an item

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#309]
On the Librarian view for an individual appointment (e.g., https://circulate-staging.herokuapp.com/admin/appointments/8 ), the UI around adding an item is a bit confusing.

Make the following alterations (see mock-up below):
- Remove the "Item" text above the search/pull-down box
- tighten the vertical space between the box and the text preceding it; there's no reason to have more than a few pixels of space
- Change the text on the button from "Create Appointment Hold" to "Add Item".

![appointment](https://user-images.githubusercontent.com/7916357/96190715-ab22a580-0f10-11eb-9d21-ce18ad36270b.png)

**Comment by italomatos** [comment]
@rkim00 is there some screenshot? Or more description about this issue?

**Comment by rkim00** [comment]
I haven't finished writing up the issue... lots of Hacktoberfest changes to keep track of. Details coming!

**Comment by rkim00** [comment]
@italomatos I've added details to this issue now!

**Comment by italomatos** [comment]
@rkim00 thank you for details
