### ISSUE TITLE
Librarian Appointments: Update text for when no appointments.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#312]
On pages where there are no appointments (e.g., https://circulate-staging.herokuapp.com/admin/appointments?day=2020-10-13 ), mainwell message is

"No matching appointsments for this day!"

Change this error message to be a little more simple and fix typo ("appointsments"):

"No appointments scheduled for this day."
[Note that we want to remove "!"]

**Comment by avinashupadhya99** [comment]
This should be fairly easy, can I pick this up?

**Comment by rkim00** [comment]
Thanks for being so active on our repo! I've sent you an invite to be a contributor; the invite should be in your e-mail. If you accept, you can assign issues yourself, rather than waiting to be assigned.

**Comment by avinashupadhya99** [comment]
Thanks. Glad I get to help.
