### ISSUE TITLE
Librarian Appointments page: link member names and item names

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#314]
As a librarian/staff member, I want to be able to click on member names and item names from the Appointments page, so that I can get more detail on members and items.

On pages like https://circulate-staging.herokuapp.com/admin/appointments?day=2020-10-14 :

- link the member name in the "Name" column to the appropriate member page in the Librarian view (e.g., https://circulate-staging.herokuapp.com/admin/members/585 )
- link the each item name in the "Appointment purpose" column to the appropriate item page in the Librarian view (e.g., https://circulate-staging.herokuapp.com/admin/items/14 )

**Comment by carterrwood** [comment]
Hi, here to help! Could someone assign this to me?

**Comment by rkim00** [comment]
Assigned! thank you.
