### ISSUE TITLE
Files created in Docker containers are owned by root

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#330]
Using a generator run within a Docker image ends up creating files owned by root, which can cause issues since developers are usually not running as root.

To reproduce, use any of the Rails generators, e.g.:

```console
$ docker-compose exec web rails generate migration TestMigration
```

The resulting new migration file will be owned by `root`. It should ideally be owned by the current user instead.

**Comment by dmonego** [comment]
This change looks doable! I can get a fix in, but I only have capacity to test in linux and mac.

**Comment by dmonego** [comment]
Just put in a PR for review!

- Building the image is done with a wrapper script. The documentation tracks this.
- Existing dev environments will need to clear out root owned files, especially in the `tmp` directory.
