### ISSUE TITLE
SpectreFormBuilder required label is being escaped

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#337]
The `required` label displayed by [SpectreFormBuilder](https://github.com/rubyforgood/circulate/blob/development/app/lib/spectre_form_builder.rb) is being escaped in templates, as shown at http://localhost:3000/admin/users/1/edit:

![image](https://user-images.githubusercontent.com/3331/96526983-a9285180-1244-11eb-8d6d-f6576916f0aa.png)

There is probably a string somewhere in the form builder that needs to be marked as `html_safe`.

**Comment by invacuo** [comment]
I can try to take this on ✋
