### ISSUE TITLE
Member Appointments: Fail more gracefully when no appointments.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#342]
Currently on pages like `https://circulate-staging.herokuapp.com/account/appointments`, where a member has no appointments, it's simply blank beneath the "Upcoming Appointments" header.

When a Member has no appointments, display a message below this header that says, "You have no scheduled appointments."

**Comment by ps9793** [comment]
I'll look into this one too. Thanks for the suggestion

**Comment by ps9793** [comment]
Created a pull-request. Please check and let me know if it solves the issue
