### ISSUE TITLE
Member should not be able to schedule pick-up on an item not yet returned

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#343]
Currently when a Member is #1 on the Hold list for an item, that item is listed as "Ready for pickup" on the Holds part of the My Loans & Holds page (https://circulate-staging.herokuapp.com/account), even if the item has not yet been returned.

However, before an item is listed as "Ready for pickup" for that Member, that item **should be returned**.

Fix this so that an item shows as "Ready for pickup" for a Member only after:
- the Member is first in line in the Holds queue, AND
- the item has been returned.

**Comment by chaserx** [comment]
Development Notes

From some initial investigation, I think that looking at the `render_hold_status` helper method first could be a good start https://github.com/rubyforgood/circulate/blob/54f7fc72221a972c9728be25a1c2875c11e3aa3a/app/helpers/holds_helper.rb#L18

**Comment by chaserx** [comment]
From the criteria:
- the Member is first in line in the Holds queue, AND
- **the item has been returned**.

The following seems like the following should be a quick fix for this issue with the result shown below. 

```diff
def render_hold_status(hold)
    previous_holds_count = hold.previous_active_holds.count
    appointment = hold.upcoming_appointment

    if appointment
      "Scheduled for pick-up at #{format_date(appointment.starts_at)} " +
      format_time_range(appointment.starts_at, appointment.ends_at)
-    elsif previous_holds_count == 0
+    elsif previous_holds_count == 0 && hold.item.available?
      "Ready for pickup. Schedule by #{format_date(hold.created_at + 7.days)}"
    else
      "##{previous_holds_count} on wait list"
    end
  end
```

<img width="551" alt="Screen Shot 2020-10-25 at 5 53 19 PM" src="https://user-images.githubusercontent.com/7292/97120081-0dd32880-16eb-11eb-9b21-09c5e0abd707.png">

Confusingly, a test far away from this helper breaks with that simple change. Which is odd to that I wouldn't expect a helper change to break any model logic. 

https://github.com/rubyforgood/circulate/blob/ded43468d5af2dad94fb2153fe80b104c1251abe/test/models/loan_test.rb#L279-L285

**Comment by chaserx** [comment]
However, this works without causing a failure elsewhere

```diff
def render_hold_status(hold)
    previous_holds_count = hold.previous_active_holds.count
    appointment = hold.upcoming_appointment

    if appointment
      "Scheduled for pick-up at #{format_date(appointment.starts_at)} " +
      format_time_range(appointment.starts_at, appointment.ends_at)
-    elsif previous_holds_count == 0
+    elsif previous_holds_count == 0 &&  hold.item.loans.last.ended?
      "Ready for pickup. Schedule by #{format_date(hold.created_at + 7.days)}"
    else
      "##{previous_holds_count} on wait list"
    end
  end
```
