### ISSUE TITLE
Librarian view: Display Item Number on Holds page

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#345]
On the Librarian Holds page (https://circulate-staging.herokuapp.com/admin/holds), add a Number column that shows the inventory item for the tool, similar to the Loans page (https://circulate-staging.herokuapp.com/admin/loan_summaries).

Put this to the right of the Name column.

**Comment by ravenblack24** [comment]
I'd like to try and help with this one please

**Comment by ps9793** [comment]
can i start working on this ?

**Comment by rkim00** [comment]
@ravenblack24 give it a shot!

**Comment by rkim00** [comment]
@ps9793 if you're still looking for an issue, #342 is a pretty simple one.

**Comment by ps9793** [comment]
> @ps9793 if you're still looking for an issue, #342 is a pretty simple one.

I'll start working on it
