### ISSUE TITLE
Hide password inputs from member profile edit page (there is a separate password change page that handles this).

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#347]
On the Member Edit Profile page (https://circulate-staging.herokuapp.com/account/member/edit) remove the Password and Password confirmation form fields and labels, since there is a separate page to edit the password. Since this form is shared with another page in the Librarian view, we'll just want to hide these two fields from this page.

**Comment by ps9793** [comment]
can I start working on this ?

**Comment by rkim00** [comment]
Sure, it's yours.

**Comment by ps9793** [comment]
Thanks

**Comment by ps9793** [comment]
Should I just remove the two fields or should I add something in it's place too ?

**Comment by ps9793** [comment]
I have created a pull-request for the branch, let me know if it is as per your expectations

**Comment by rkim00** [comment]
You should just hide/remove them, so that the space that they occupy is collapsed. Thanks for your contribution! @jim will review and merge when he has a second.
