### ISSUE TITLE
Update e-mails

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#352]
We need to update e-mails across Circulate to account for changes to the app over the last few months.

Circulate e-mail previews can be viewed at https://circulate-staging.herokuapp.com/rails/mailers . Note that changes need to happen for both the plaintext versions and HTML versions of the e-mails. Plaintext versions may have gotten out of date with the HTML versions; if it's unclear how to update the plaintext version, feel free to use your best judgement or make a note and we can fix in a separate issue.

Here are the updates:

### Multiple e-mails: 
- [ ] "Need to return tools?" blue box that appears in several emails: replace all text with "Need to return or pick-up tools? Schedule a time here!" with link to `https://app.chicagotoollibrary.org/account/appointments/new` . This link will be broken for now, but should be fixed by the time this deploys.

### Gift purchase email: 
- [ ] change this text
> Once we review the above, they'll be ready to borrow for one year beginning on the date they come in.

to "Once we review the above, their one-year membership will begin on the day they borrow their first tool."

### Due soon and overdue emails: 
- [ ]  remove use of word "are" in member waiting reminder. Ex. say "1 member waiting for this item" vs. current "1 member are waiting for this item"

### Membership reminder email:
- [ ]  remove 
> More details on what to bring when you come in are at the bottom of this message.  If you'd like to check for a specific item before coming in, you can view our tool inventory online. We're adding new tools to our collection all the time!

and replace with "Create your library member login now to update your contact information, browse our tool inventory, and request your first tool pick-up!" with link to chicagotoollibrary.org/member-login (this page is blank now, but should have info by the time this deploys)
- [ ] remove keypad info
> To get inside, dial 008 on the keypad or come through the loading dock (our door is up the ramp and in the corner).

### Welcome email: 
- [ ] remove keypad info and replace with "Create your library member login now to update your contact information, browse our tool inventory, and schedule your first tool pick-up!" with link to chicagotoollibrary.org/member-login  (this page is blank now, but should have info by the time this deploys)

**Comment by PeterGillis** [comment]
I'd like to help out but cant seem to find the usual contribute buttons.  Perhaps I'm being daft and cant see something obvious?

**Comment by rkim00** [comment]
@PeterGillis This one is VERY preliminary—not much to do on it yet. You might check for other issues in the meantime (https://github.com/rubyforgood/circulate/labels/hacktoberfest)

That having been said, I think you need to branch and make a pull request in order to contribute. Does that help at all?

**Comment by tessavierk** [comment]
I added details to this!

**Comment by rkim00** [comment]
@jim @tessavierk I took a pass at making this a little clearer for folks to work on, but had several questions along the way, which I put into the issue itself. Can one or both take a pass and fix? Feel free to simply make the edits rather than answering my questions directly.

**Comment by rkim00** [comment]
@jim @tessavierk FYI, the membership reminder e-mail had the "Create your library member login now..." info in two places, so I removed one of them.
