### ISSUE TITLE
Add footer to all member-facing pages

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#353]
Add a footer to all member-facing pages. Make similar color and style to the top brown bar on the admin pages (e.g., https://circulate-staging.herokuapp.com/admin), but add to the bottom of the page, obviously.

Centered white text on the footer should read, "For questions and issues please email team@chicagotoollibrary.org"

No need to spend tons of time on design / layout; we'll likely make some tweaks after it's been put up.

Examples of pages it should be added to:
- My Loans (https://circulate-staging.herokuapp.com/account)
- Inventory (https://circulate-staging.herokuapp.com/items)
- Search (https://circulate-staging.herokuapp.com/search?query=saw)

It should NOT be added to pages like https://circulate-staging.herokuapp.com/admin
Other pages like Sign-up or Login are edge cases... they don't need a footer but probably it would be okay if it were added. If it's easier to add, add a comment and we'll discuss.

**Comment by efgalvao** [comment]
Can I try this one ?

**Comment by rkim00** [comment]
Yes, it's yours! Thank you very much!

**Comment by jim** [comment]
Fixed by #360
