### ISSUE TITLE
Member can cancel appointment

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#354]

**Comment by avinashupadhya99** [comment]
Hey @rkim00 , I was thinking about having an option where members can either **cancel** their appointments or **reschedule** their appointments. Thoughts?

**Comment by rkim00** [comment]
Yes, that's a perfectly good option as well. We haven't really thought about how this would work from a UI standpoint yet. What are your ideas?

**Comment by avinashupadhya99** [comment]
I think we should just handle the cancelling part with this issue and take up the rescheduling part in #369

**Comment by rkim00** [comment]
Hi @avinashupadhya99 , thanks for taking the initiative with this! Really appreciate it. Looks pretty good to me, although @jim may have more to say. Two things I wanted to check on:

1) Am I correct that the appointment itself is cancelled, but the associated hold is unaffected? So that after the member cancels an appointment, they keep their place in line for whatever hold they have?

2) Should we have any new tests to cover this functionality? (I may have missed them in the commit.)

**Comment by avinashupadhya99** [comment]
Yes, only the appointment will be cancelled. The holds are unaffected by this. 
I'll see if I can add test cases for this.
