### ISSUE TITLE
Member pages: Update text next to held item after scheduled.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#355]
Currently, on several Member's pages:
- My Holds pages (https://circulate-staging.herokuapp.com/account)
- Schedule an Appointment (https://circulate-staging.herokuapp.com/account/appointments/new)
- Upcoming Appointments (https://circulate-staging.herokuapp.com/account/appointments)

... the text next to a Hold is always displaying as "Ready for pickup. Schedule by [date]", even when the item has been scheduled for pick-up.
![appts](https://user-images.githubusercontent.com/7916357/96887058-2ffe4980-1452-11eb-97c5-2a022bd85757.png)

Fix this so that after an Item is scheduled (associated with an Appointment Date), this text instead reads
"Scheduled for pick-up [appointment date, [appointment time]".

Related to #356 , #357 .

**Comment by kevinluo201** [comment]
May I try to solve this one? : )

**Comment by rkim00** [comment]
Please! Thank you!
