### ISSUE TITLE
Member My Holds: Update text next to checked-out item after scheduled for return.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#356]
Currently, on several Member's pages—
- My Holds pages (https://circulate-staging.herokuapp.com/account)
- Schedule an Appointment (https://circulate-staging.herokuapp.com/account/appointments/new)
- Upcoming Appointments (https://circulate-staging.herokuapp.com/account/appointments)

—the text next to a Loan is always displaying as "overdue", or "check-out" even when the item has been scheduled for return.

![appts](https://user-images.githubusercontent.com/7916357/96902654-caff1f80-1462-11eb-8637-c7558888ef0f.png)

This is somewhat confused for the Member, since they've now scheduled this item for return and there's no status change.

Fix this so that after an Item is scheduled (associated with an Appointment Date), we append under "overdue" or "checked-out" 
"Scheduled for return [appointment date, [appointment time]". E.g.,

> overdue
> Scheduled for return Sat, 10/27, 11am

Depending on spacing and layout, we may alternately want to put it on the same line instead of a separate line, in which case "overdue" or "checked-out" should be capitalized and there should be a period in-between and after. E.g.,

> Overdue. Scheduled for return Sat, 10/27, 11am.

Related to #355 , #357 .

**Comment by oLeVanNinh** [comment]
Can I take this?

**Comment by rkim00** [comment]
Sure. Thanks!

**Comment by oLeVanNinh** [comment]
Seem like it has addressed!

**Comment by rkim00** [comment]
Sorry about that—thanks!
