### ISSUE TITLE
Admins can edit member notes

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#370]
This is a follow-on to #366. 

* Make the link to edit modal notes in the modal go to a new page that contains an edit form for that note.
* When the note is updates successfully, redirect to the member's profile page.
* A nice-to-have is adding a "delete" note to the bottom of the edit form, which allows admins to delete that note.

**Comment by preethinarayan** [comment]
@jim could I take a stab at this?

**Comment by rkim00** [comment]
@preethinarayan assigning to you!

**Comment by jim** [comment]
This was closed by #406
