### ISSUE TITLE
Fix footer display on Items page

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#374]
Footer ("For questions and issues...") is displaying in middle of page on items page (e.g., https://circulate-staging.herokuapp.com/items/36 ).
![footer](https://user-images.githubusercontent.com/7916357/97314034-a974ae00-183d-11eb-817f-def79ad4994d.png)

Fix so that it displays at the bottom of the page.

**Comment by efgalvao** [comment]
Can I try this one ?

**Comment by rkim00** [comment]
You got it! Thanks!
