### ISSUE TITLE
Librarian Appointment Page - update item count after checking out item

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#379]
Currently, on the Librarian VIew/Edit Appointment page (e.g., https://circulate-staging.herokuapp.com/admin/appointments/5 ), the number of checked-out items doesn't update correctly after checking out an item.
![appt](https://user-images.githubusercontent.com/7916357/97326905-d8455100-184a-11eb-89a1-68d51ad92501.png)

Fix this so that the number of items to be checked-out is always correct.

Probably worth checking to make sure that this works correctly for checking in items on this page as well.

**Comment by jim** [comment]
Fixed by #385
