### ISSUE TITLE
Test failure with specific seed value

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#382]
Running `/rails test --seed 31967` will result in the following test failure:

```
Failure:
LoanTest#test_is_member_renewable_if_borrow_policy_allows_member_renewal_is_within_original_loan_duration_and_has_not_exceeded_limit [/Users/jimb/code/circulate/test/models/loan_test.rb:285]:
Expected false to be truthy.
```

This tests doesn't fail when running `rails test test/models/loan_test.rb`, so it seems to be related to how the test data is being setup. I think it has something to do with the `Loan#within_borrow_policy_duration?`.

I'm not totally sure if we need this method, or what it is used for. It's possible that we should just remove it and its uses; otherwise, we should add some tests abound its behavior.

**Comment by invacuo** [comment]
I would like to take this one on
