### ISSUE TITLE
Create a flow for members to renew their memberships online.

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#422]
- Show banner on top, with button that would take folks to renewal form
- Renewal form will just be same sign-up form—maybe tweak the text
- Enter amount and pay
- Use same flow to start with

Re-agree?
- May need to re-agree if agreement has changed since last agreement
- we track when folks have agreed
- we know when updated (from database), but we don’t know how

Re-agree is a bit hairy—maybe need to leave for later.

**Comment by jim** [comment]
This is completed and has shipped!
