### ISSUE TITLE
Remove pronoun and custom_pronoun columns from members table

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#443]
**Is your feature request related to a problem? Please describe.**
We migrated pronoun data into a new column, `pronouns`, and need to remove the vestigial `pronoun` and `custom_pronoun` columns.

To do this, we will need to create a migration that removes these two columns. It's also worth looking through the code to see if there are any dangling references to these columns and make appropriate fixes.

**Comment by italomatos** [comment]
Hi, can I take it @jim ?

**Comment by rkim00** [comment]
@italomatos , we're going to take you off this issue for now. Feel free to add yourself back if you want to take it!

**Comment by italomatos** [comment]
thanks @rkim00 , sorry for delay, but I think I resolved this item in this PR: https://github.com/rubyforgood/circulate/pull/444 , is it?

**Comment by jim** [comment]
Whoops! You're right, @italomatos, you already did this! 😄
