### ISSUE TITLE
Librarian appointments page: Show that appointments have been picked up or dropped off

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#453]
As a librarian, I want to be able to see whether or not an appointment has taken place, so that I can see status of appointments on this page.

This could be as simple as:
- checkbox on the appointments page below the view/edit button
- when the checkbox is checked, the row is greyed
- unchecking the checkbox reverse the greying of the row
- state is stored as a boolean in the database, so that it persists for multiple users or for people leaving and coming back

**Comment by jim** [comment]
@AngelaGuardia I'm going pick this one up 😄
