### ISSUE TITLE
Members can edit appointment details (date & time, add or remove tools)

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#458]
As a member, I want to be able to edit details of a scheduled appointment, so that I don't need to create an additional appointment or e-mail the library staff to change details about it.

Per @tessavierk :
> Members are currently creating several appointments if they forget to add something to their list.

Give members the ability to edit appointment details.

One way to do this may be to create an "edit appointment" button on next to each appointment listed on the View Appointments page (https://circulate-staging.herokuapp.com/account/appointments). The edit screen could be a version of the Schedule Appointment page (https://circulate-staging.herokuapp.com/account/appointments/new), with the following characteristics:
- Items that are already scheduled for return or pick-up are pre-checked, and can be unchecked to be removed from the appointment after submit
- Items that are not scheduled for return but that are eligible (i.e., are checked out) are unchecked, and can be checked to add to the appointment after submit
- Items that are not scheduled for pick-up but that are eligible (i.e., are on hold and user is first in line) are unchecked, and can be checked to add to the appointment after submit
- Date and time are selected in pull-down but a different day or time can be selected. (RK: This might work a little funny with the current date/time selection process, which I recall might be in two steps. I'm not able to look at it right now... but do what seems to make the most sense.)
- Members should probably be able to select a different date in the "Tell us about the project you are working on" box.
- Submit button should probably be "Update Appointment" or similar instead of "Edit Appointment"
- We should probably have "Cancel" button that takes users back to the Appointments change and doesn't change anything.

**Comment by stephanieminn** [comment]
hello! I can take this and get to it this week. can you assign to me? :)

**Comment by jim** [comment]
This was completed in #500.
