### ISSUE TITLE
Categories on item pages should be links

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#482]
Being able to click on the categories associated with an item would allow users to browse for similar items.

In the following example, *Kitchen* should be a link to the items inventory page filtered by that category:

![image](https://user-images.githubusercontent.com/3331/112098498-e5ebd200-8b6f-11eb-85ca-468e81e7b21e.png)

**Comment by hairedfox** [comment]
@jim I'd love to take this issue :D Thank you in advance

**Comment by jim** [comment]
This was completed in #511
