### ISSUE TITLE
Borrow Policies NameError in Admin::BorrowPolicies#index 

### ISSUE THREAD

**Issue by kthomasak** [rubyforgood/circulate#528]
**Describe the bug**
Fresh install, when clicking on Borrow Policies I get the following

> NameError in Admin::BorrowPolicies#index
> 
> Showing /usr/src/app/app/views/shared/_empty_state.html.erb where line #9 raised:
> 
> undefined local variable or method `new_admin_borrow_policy_path' for #<ActionView::Base:0x00000000012598>
> Did you mean?  edit_admin_borrow_policy_path
> 
> Extracted source (around line #30):
> 
> <% else %>
>   <%= empty_state "There are no borrow policies.", subtitle:"Create one?" do %>
>     <%= link_to "Add a Borrow Policy", new_admin_borrow_policy_path, class: "btn btn-primary" %>
>   <% end %>
> <% end %>
> 
> Trace of template inclusion: #<ActionView::Template app/views/admin/borrow_policies/index.html.erb locals=[]>
> 
> Rails.root: /usr/src/app
> Application Trace | Framework Trace | Full Trace
> app/views/admin/borrow_policies/index.html.erb:30
> actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
> actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
> actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:45:in `capture'
> actionview (6.1.3.1) lib/action_view/helpers/rendering_helper.rb:102:in `_layout_for'
> actionview (6.1.3.1) lib/action_view/renderer/partial_renderer.rb:286:in `block (2 levels) in render_partial_template'
> app/views/shared/_empty_state.html.erb:9
> actionview (6.1.3.1) lib/action_view/base.rb:247:in `public_send'
> actionview (6.1.3.1) lib/action_view/base.rb:247:in `_run'
> actionview (6.1.3.1) lib/action_view/template.rb:154:in `block in render'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:205:in `instrument'
> actionview (6.1.3.1) lib/action_view/template.rb:345:in `instrument_render_template'
> actionview (6.1.3.1) lib/action_view/template.rb:152:in `render'
> actionview (6.1.3.1) lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
> activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
> actionview (6.1.3.1) lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
> actionview (6.1.3.1) lib/action_view/renderer/partial_renderer.rb:271:in `render'
> actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
> actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:53:in `render_partial'
> actionview (6.1.3.1) lib/action_view/helpers/rendering_helper.rb:45:in `render'
> app/helpers/admin_helper.rb:15:in `empty_state'
> app/views/admin/borrow_policies/index.html.erb:29
> actionview (6.1.3.1) lib/action_view/base.rb:247:in `public_send'
> actionview (6.1.3.1) lib/action_view/base.rb:247:in `_run'
> actionview (6.1.3.1) lib/action_view/template.rb:154:in `block in render'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:205:in `instrument'
> actionview (6.1.3.1) lib/action_view/template.rb:345:in `instrument_render_template'
> actionview (6.1.3.1) lib/action_view/template.rb:152:in `render'
> actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
> activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
> actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
> actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
> activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
> actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
> actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
> actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:11:in `render'
> actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
> actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
> actionview (6.1.3.1) lib/action_view/rendering.rb:117:in `block in _render_template'
> actionview (6.1.3.1) lib/action_view/base.rb:273:in `in_rendering_context'
> actionview (6.1.3.1) lib/action_view/rendering.rb:116:in `_render_template'
> actionpack (6.1.3.1) lib/action_controller/metal/streaming.rb:218:in `_render_template'
> actionview (6.1.3.1) lib/action_view/rendering.rb:103:in `render_to_body'
> actionpack (6.1.3.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
> actionpack (6.1.3.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
> actionpack (6.1.3.1) lib/abstract_controller/rendering.rb:25:in `render'
> actionpack (6.1.3.1) lib/action_controller/metal/rendering.rb:36:in `render'
> actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
> benchmark (0.1.1) lib/benchmark.rb:308:in `realtime'
> activesupport (6.1.3.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
> actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
> actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
> activerecord (6.1.3.1) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
> actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:45:in `render'
> turbolinks_render (0.9.20) lib/turbolinks_render/rendering.rb:8:in `render'
> actionpack (6.1.3.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
> actionpack (6.1.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
> actionpack (6.1.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
> actionpack (6.1.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
> actionpack (6.1.3.1) lib/abstract_controller/base.rb:228:in `process_action'
> actionpack (6.1.3.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
> actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
> app/controllers/application_controller.rb:23:in `override_time_in_development'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
> app/controllers/application_controller.rb:34:in `block in set_time_zone'
> activesupport (6.1.3.1) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
> app/controllers/application_controller.rb:32:in `set_time_zone'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
> audited (7fd8334edf68) lib/audited/sweeper.rb:14:in `around'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
> audited (7fd8334edf68) lib/audited/sweeper.rb:14:in `around'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
> actiontext (6.1.3.1) lib/action_text/rendering.rb:20:in `with_renderer'
> actiontext (6.1.3.1) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `instance_exec'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
> sentry-raven (2.13.0) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `instance_exec'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
> actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
> actionpack (6.1.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
> actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
> activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
> actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
> actionpack (6.1.3.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
> activerecord (6.1.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
> actionpack (6.1.3.1) lib/abstract_controller/base.rb:165:in `process'
> actionview (6.1.3.1) lib/action_view/rendering.rb:39:in `process'
> actionpack (6.1.3.1) lib/action_controller/metal.rb:190:in `dispatch'
> actionpack (6.1.3.1) lib/action_controller/metal.rb:254:in `dispatch'
> actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
> actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
> actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
> actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
> actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
> actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
> omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
> omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
> omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
> warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
> warden (1.2.9) lib/warden/manager.rb:34:in `catch'
> warden (1.2.9) lib/warden/manager.rb:34:in `call'
> rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
> rack (2.2.3) lib/rack/etag.rb:27:in `call'
> rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
> rack (2.2.3) lib/rack/head.rb:12:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
> rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
> rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
> activerecord (6.1.3.1) lib/active_record/migration.rb:601:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
> activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
> appsignal (3.0.2) lib/appsignal/rack/rails_instrumentation.rb:19:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
> web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
> web-console (4.1.0) lib/web_console/middleware.rb:19:in `block in call'
> web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
> web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
> turbolinks_render (0.9.20) lib/turbolinks_render/middleware.rb:81:in `call'
> gems/active_storage_log_suppressor/lib/active_storage_log_suppressor/filters.rb:45:in `call_app'
> railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
> activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
> activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
> activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
> railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
> rack (2.2.3) lib/rack/method_override.rb:24:in `call'
> rack (2.2.3) lib/rack/runtime.rb:22:in `call'
> activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/static.rb:24:in `call'
> rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
> actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
> sentry-raven (2.13.0) lib/raven/integrations/rack.rb:51:in `call'
> webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
> rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
> railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
> puma (5.2.1) lib/puma/configuration.rb:247:in `call'
> puma (5.2.1) lib/puma/request.rb:76:in `block in handle_request'
> puma (5.2.1) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
> puma (5.2.1) lib/puma/request.rb:75:in `handle_request'
> puma (5.2.1) lib/puma/server.rb:431:in `process_client'
> puma (5.2.1) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
> logging (2.3.0) lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
> Request
> 
> Parameters: None
> 
> Toggle session dump
> Toggle env dump
> Response
> 
> Headers: None

**To Reproduce**
Click Borrow Policies

**Expected behavior**
Should load a page where I can add or review borrow policies

**Comment by kthomasak** [comment]
I also can't add new items because there are now borrow policies and it's a required item

**Comment by kthomasak** [comment]
no thoughts? sadly looks like I'll be pursuing a "paid" option for our needs but this had so much promise.

**Comment by jim** [comment]
@kthomasak Sorry to hear you had trouble. We're all volunteers and aren't always able to respond to all issues as fast as we'd like. We highly recommend that you join us [in the Ruby For Good Slack](https://rubyforgood.herokuapp.com/) in the #circulate channel if you need a response within a certain amount of time.

In any case, if you run `bin/setup` it will create a set of default BorrowPolicies for you. If that doesn't work, please let us know and I'll see what is going on.

Cheers!
