### ISSUE TITLE
Change field label in item creation/editing from "Other Names" to "Other names and keywords"

### ISSUE THREAD

**Issue by CTLvivek** [rubyforgood/circulate#605]
In librarian view, when creating a new item (https://circulate-staging.herokuapp.com/admin/items/new), currently there's a field called "Other Names". Change it to "Other names and keywords".

This is to make it more clear to people entering data what type of data is useful in this box. For example, with a vacuum sealer there's no other name, but phrases like "sous vide" or "preservation" and "preserve" would be very useful search terms.

**Comment by rkim00** [comment]
@CTLvivek and @jim —I think "search terms and other names" could be a bit confusing. As a user, I don't think I'd know what "search terms" means immediately. What about "Other names and search terms" or "Other names and keywords"? Then people are prompted more to think about "other names" first, which flows more naturally from "Name" above it. I think we could also revise the text below the box to be a little clearer.

**Comment by CTLvivek** [comment]
Yep, "other names and keywords" works well. Keywords is a big improvement over search terms.  I mostly put Search terms first in the title because I didn't want people to get stuck on the idea of other names because many items don't have useful other names.

**Comment by stephanieminn** [comment]
👋 working on this one too in https://github.com/rubyforgood/circulate/pull/642
