### ISSUE TITLE
Librarian view: Add "pronunciation" field to member so we know how to say their names

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#630]
We'd like to know how to properly pronounce someone's name when they come in to visit the library.

To accomplish this, we need to:

* Add a new string column, `pronunciation`, to the `members` table.
* Add this field to the admin member form but not the member's own member form.
* Add the pronunciation to the  left sidebar on the admin member page using the `volume-2` feather icon. It should appear after their pronouns. This will require changes to `https://github.com/rubyforgood/circulate/blob/main/app/views/admin/members/_member_details.html.erb`.

**Comment by lamphanqg** [comment]
I'm working on this.
