### ISSUE TITLE
Update application to Rails 6.1 defaults

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#631]
`config/application.rb` currently has the framework defaults set to those from Rails 6.0. Updating this was a step of the 6.1 upgrade that was missed.

We need to change this value to `6.1` and make any other changes to the application to keep its existing behavior. [Here is a list of what values will change](https://guides.rubyonrails.org/configuring.html#for-6-1-defaults-from-previous-versions-below-and).

**Comment by pjsier** [comment]
Should be closed by #648, but feel free to reopen if I missed anything!
