### ISSUE TITLE
Cannot update member's bio

### ISSUE THREAD

**Issue by lamphanqg** [rubyforgood/circulate#651]
**Describe the bug**
In member edit page of librarian view, if I input bio and update, the update is successful but bio field is not updated. This is due to `member_params` in `members_controller.rb` does not permit `bio`.

**To Reproduce**
1. Login to admin and go to http://localhost:3000/admin/members/8/edit
2. Input something into Bio field
3. Click Update Member
4. See the bio is not saved

**Comment by jim** [comment]
Fixed by #727
