### ISSUE TITLE
Remove "Check-in all" and "Check-out all" buttons from the appointment window.

### ISSUE THREAD

**Issue by CTLvivek** [rubyforgood/circulate#669]
There has been an increase in false check-ins and check-outs lately and that will likely continue as more volunteers get involved in the space and there is greater throughput in member interactions. 

Removing these two buttons will force librarians to take more time with individual transactions and be less likely to mistakenly check something in or out when it wasn't actually involved in the interaction.  (common example, a member will create an appointment to return items but forget one of the items on the appointment. Clicking "check-in all" would create a phantom tool in the library and cause issues if someone is waiting in line for that tool.

**What to do**

Perhaps as training improves or something else changes it'll be nice to have this functionality back, so if possible please just remove the buttons from the librarian UI but maintain the functionality. 

_Let's just comment out the buttons until we figure out if we want to remove this for good!_

![checkin button](https://user-images.githubusercontent.com/86161788/133679940-a99d33db-9ebc-4eb4-9766-9591352ab989.JPG)

**Comment by jim** [comment]
Fixed by #724
