### ISSUE TITLE
Update optional notes field label in the appointment scheduling window

### ISSUE THREAD

**Issue by CTLvivek** [rubyforgood/circulate#676]
As a librarian, I'd like to reduce the overhead in member-librarian interactions at the library.  Right now, we are trying to collect a lot of information in a very short period of time. As a result, information can get loss pretty easily.

**Why this is important**

I'd like to change the language to de-emphasize the optionality and also make mention of leaving feedback for drop-offs.

New language:

> Tell us about the project you're working on. We may be able to recommend a different or additional tool. If you're dropping off, please let us know if you had any issues with the items you're returning.

![appointment language](https://user-images.githubusercontent.com/86161788/133868033-50a927d6-5b44-4dca-8667-bb0cccd98666.JPG)

**Comment by jim** [comment]
Fixed by #739
