### ISSUE TITLE
Hyperlink tools or tool numbers when viewing a member's appointment

### ISSUE THREAD

**Issue by CTLvivek** [rubyforgood/circulate#677]
Per Vivek:
> It'd be useful to be able jump directly to a tool to get more details about it or understand the loan/hold history. Currently, if in the window of a member's appointment, librarians have to search for the tool with the inventory search.

![appointment hyperlink request](https://user-images.githubusercontent.com/86161788/133868537-92120129-9271-4875-bbf3-e2855aaea5ee.JPG)

RK notes:
- I believe Vivek means that the tool name or number should link to the display page for that tool in the Librarian side, not the Member/User side.
- Small preference for linking the tool name here, but developer's choice depending on what seems to make the most intuitive sense.
- I suspect simply linking is better than generating a pop-up or new window, but again, see what you think when you implement.

**Comment by jim** [comment]
Closed by #738
