### ISSUE TITLE
Add renewal copy to item emails

### ISSUE THREAD

**Issue by tessavierk** [rubyforgood/circulate#695]
Emails about tools that are due needs to have link/text option for renewals (currently only has links/text about pick-ups and drop-offs).

Add the following text to [the "summary" email template](https://github.com/rubyforgood/circulate/blob/main/app/views/member_mailer/summary.mjml#L21-L26), where "your account page" is a link to that member's account page for loans.

> Request a renewal for your tools or schedule a drop-off on your account page.

**Comment by tessavierk** [comment]
**Request a renewal for your tools or schedule a drop-off here.** (link to member profile)

**Comment by RachelWyatt** [comment]
Hi @jim is this being worked on or can I take it?

**Comment by jim** [comment]
@RachelWyatt It’s all yours!
