### ISSUE TITLE
[dev] Some mailer previews are not working.

### ISSUE THREAD

**Issue by robbkidd** [rubyforgood/circulate#743]
### Describe the bug

Some of [the mailer previews](https://guides.rubyonrails.org/action_mailer_basics.html#previewing-emails) in the development environment raise an exception instead of rendering.

### To Reproduce

1. Fire up the Rails app.
2. Go to `localhost:3000/rails/mailers/`

#### Couldn't find GiftMembership

* Under "Gift Purchaser Mailer", click on "confirmation".
    * BEHOLD! A GiftMembership cannot be found!

#### No query results

* Under "Member Mailer", click on either "due_soon", "items_on_hold".
    *  BEHOLD! An error indicating that the `loan_summaries` query result is empty (`.first` returned `nil`).

#### Association with a Library is missing

 * Under "Member Mailer", click on any of "hold_available", "membership_reminder", "membership_renewal_reminder", "renewal_message", "renewal_request_approved", "renewal_request_rejected", or "staff_daily_renewal_requests".
     * BEHOLD! An error about libraries, either a missing required Library relation or a local variable named `library` cannot be found.

### Expected behavior

The email previews ought to render without error.

### Additional context

My theory is that Library relationships appeared in the models and the fixture-ish activity in the preview methods need to catch up to those changes.

**Comment by jim** [comment]
Closed by #756
