### ISSUE TITLE
Show a members place in line on the member hold screen

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#75]
On the member's holds screen, show that person's position in line for each hold. Let's put it under the cancel button like this:

<img width="648" alt="Screen Shot 2020-07-06 at 9 01 44 PM" src="https://user-images.githubusercontent.com/3331/86689227-6bbcf280-bfcc-11ea-9147-db52655ff0b6.png">

RK note: I believe this is on the admin side. Example URL: https://circulate-staging.herokuapp.com/admin/members/589/holds

**Comment by preethinarayan** [comment]
@jim could I give this a shot?

**Comment by rkim00** [comment]
Assigned to you! Thanks!

**Comment by rkim00** [comment]
Updated the description slightly to clarify.
