### ISSUE TITLE
Add appointment count to Activity Report

### ISSUE THREAD

**Issue by rkim00** [rubyforgood/circulate#752]
We'd like to add a new bit of information to the Activity Report: how many appointments were scheduled per month.

Here's the current report:

![image](https://user-images.githubusercontent.com/3331/136809217-b4bca296-2864-431c-9498-d083bce59026.png)

1. We'd like there two be a new column under `Activity` called `Appointments`.
2. The value for each column should be the total number of scheduled appointments during that month. 
3. Show the number of completed appointments in parenthesis in the same cell would be great.

So if there were 10 total appointments in a month and 8 of those were completed, the cell would show "10 (8)".

**Comment by KFad11** [comment]
Working on it!

**Comment by jim** [comment]
@KFad11 Do you want to keep this issue, or should we put it back in the pool for someone else to pick up?

**Comment by KFad11** [comment]
@jim Hey! Yes, sorry about that, I did not think buying a house would be like picking up a 2nd full time job but it turned out to be a major time sink. We're all settled now and I'm almost code complete on this. Let me get it finished up ASAP.

**Comment by KFad11** [comment]
Hey Jim, I'll be working on this this week for y'all. Last week I was on vacation down in Cancun at Power's holiday party, so available time was a little scarce. I was able to update my local env with the changes while down there though, I've got the view updated and looking good, just need to sync the numbers up with the appointments.

**Comment by jim** [comment]
That's great! We'll keep an eye out for your changes.

**Comment by KFad11** [comment]
My plan to take this over after vacation got sidetracked by COVID >.< It was not meant to be for me on this issue, Jim. I'm on the mend and doing better but not out of the woods yet. I'm sure this being a good first issue for someone who has the capacity to pick it up would be better off with it than me at this moment.

When things settle down in the new year I'll be sure to give the board a look and maybe take some VTO time from Power to focus my efforts a bit better and not tie something up for this long. Sorry about that!

**Comment by shkm** [comment]
Happy to pick this up.
