### ISSUE TITLE
Add a nice 404 page

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#774]
**Is your feature request related to a problem? Please describe.**

When attempting to view a page that doesn't exist, users get a default 404 page that doesn't seem to belong to the rest of the site (because it doesn't!). [Here is an example](https://app.chicagotoollibrary.org/items/123123).

**Describe the solution you'd like**
It would be nice to see a simple "that page could not be found" message rendered within the normal site navigation, etc.

**Comment by kinduff** [comment]
Happy to take this one @jim !
