### ISSUE TITLE
Inventory search should filter the main inventory page

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#784]
**Is your feature request related to a problem? Please describe.**

When a user searches for an item on the public inventory pages, they are taken to a search results page like [this one](https://app.chicagotoollibrary.org/search?query=key).

**Describe the solution you'd like**
1. When a user searches in the header search box for `your query`, they should see their search results in the form of a filtered inventory page with only matching items appearing in the list:
  ![image](https://user-images.githubusercontent.com/3331/136724726-790b8fe4-0f6d-453d-b92d-18e3caa0e8c8.png)

2. If a user clicks on a category name, that category should be added as another filter:
  ![image](https://user-images.githubusercontent.com/3331/136725075-3f99d6c6-2fb2-4e0e-b403-121eba191936.png)

3. We can also remove the public search controller, views, etc.

**Describe alternatives you've considered**

**Additional context**

The images above are just mockups. A nicer UI for searching and filtering would be welcomed. There is a separate story to add another filtering option to the public inventory pages: #672

**Comment by shkm** [comment]
I'd be happy to pick this one up.

**Comment by jim** [comment]
@shkm It's all yours!
