### ISSUE TITLE
Membership report is not working

### ISSUE THREAD

**Issue by CTLvivek** [rubyforgood/circulate#808]
**Describe the bug**
The report for membership isn't working. 

**To Reproduce**
1. Sign in to Circulate as an admin
2. Go to 'https://app.chicagotoollibrary.org/admin/reports/memberships' or click on Reports -> Membership (this is the way I did it when encountering the error)
3. See error

**Desktop (please complete the following information):**
 Windows, Chrome, latest version

**Additional context**
Not urgent. I honestly can't even remember what the membership report did but I'm creating this issue just in case it's related to something more important.

**Comment by jim** [comment]
Fixed by #861
