### ISSUE TITLE
Improve language on holds page

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#83]
> This is maybe nit-picky, but I think a lot about plain language and I feel like these sentence structures could be tough for those without great English skills "To request items be held for you, search for them below.
Then click Continue to proceed to confirm your account and select when to pickup those items." maybe instead "Search for tools below. Click continue to confirm your account and choose a pick-up time."

> Maybe also say something like "If you choose a tool that is checked-out you will be added to the wait list for that tool"

Make the above changes.

**Comment by efgalvao** [comment]
This one is done ?

**Comment by rkim00** [comment]
Yes. I think actually this whole branch of code is mostly moot now. Will close—sorry about that!
