### ISSUE TITLE
Paginated endpoints return HTTP 500 when page param exceeds number of pages of results

### ISSUE THREAD

**Issue by robbkidd** [rubyforgood/circulate#850]
**Describe the bug**

Paginated endpoints will throw an exception when the page parameter exceeds the number of pages of items to display. This exception is actively [being triggered](https://sentry.io/organizations/chicago-tool-library/issues/2580855230/) by [an enthusiastic web crawler](https://www.semrush.com/bot/). The library's user receives an HTTP 500 server error.

**To Reproduce**
1. Fire up a development instance with the devdata loaded.
2. Log in.
3. Click on "Lending" then "Items".
4. Scroll to the bottom of the page.
5. Click on the last page number available. (Currently "10")
6. After the last page loads, in the browser's location bar, change the `page=##` parameter to a number higher than the one that appears—e.g. change "10" to "11"—and press Return on the keyboard.
7. Behold! An error!

**Expected behavior**

An error of "the server can't do that" sent to the user is unexpected. The unhandled exception alerts fired are less than ideal.

Some behaviors in the realm of reasonable expectations, some of which could be combined:
* The paginated page returns empty.
* The paginated page returns the last legitimate page of results.
* The user is shown a warning on a properly rendered page of results notifying them that the page that was requested is currently invalid.

**Comment by robbkidd** [comment]
A quick application of some configuration salve will address this. We just need to decide what behavior we'd like when someone asks for a page beyond the current results.

[Pagy](https://ddnexus.github.io/pagy/) is our pagination library. It includes an "[extra](https://ddnexus.github.io/pagy/extras)" for dealing with this [pagination overflow](https://ddnexus.github.io/pagy/extras/overflow) situation. Adding these two lines to `config/initializers/pagy.rb` resolved the 500 error for me in development by returning the last page of results for any page requested above the number of pages available.

```ruby
require "pagy/extras/overflow"
Pagy::DEFAULT[:overflow] = :last_page
```

Other options are `:empty_page` (default) to display no results or `:exception` which is basically the current behavior.

My recommendation is to add those lines to the Pagy configuration and, in a bonus round, add a flash message when the page param has overflowed—detectable with [the `pagy.overflow?` predicate method](https://ddnexus.github.io/pagy/extras/overflow.html#overflow)—notifying the user of the invalid parameter.

Additionally, maybe also assess nerfing web crawlers with `public/robots.txt`.

**Comment by jim** [comment]
@robbkidd I agree with your recommendation to add the last page configuration to Pagy.
