### ISSUE TITLE
Duplicate information in gift membership email

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#860]
**Describe the bug**
There is duplicated information in the email sent to people when they've purchased a gift membership

**To Reproduce**
1. Log in as an admin
2. Go to Settings -> Gift Memberships
3. Create a new Gift Membership
4. Look at the email that is autogenerated.

**Expected behavior**
The COVID information should only appear in the email once.

**Screenshots**
![image](https://user-images.githubusercontent.com/3331/141362275-b427157d-83a7-448c-9f22-394d963bbfb4.png)

**Additional context**
There was some work done to move all emails to use a shared layout. It's possible that something was missed during that work.

**Comment by AlanGabbianelli** [comment]
Hey @jim, I can take this one.

**Comment by jim** [comment]
@AlanGabbianelli It's all yours!
