### ISSUE TITLE
Selected hold request date is not persisted

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#87]
> When I requested a hold for this afternoon(August 1),  (using the member1 test email address) the confirmed date on the Hold Request Complete page had a different date (July 30)

* The correct date must be stored
* The selected data needs to be displayed properly

**Comment by robbkidd** [comment]
While something like this issue may be present, I think enough has changed in the flow of scheduling an appointment that the problematic behavior is no longer as described here. Could be we should close or rewrite this issue.

**Comment by jim** [comment]
I agree. Let's close until it pops up again.
