### ISSUE TITLE
Only include data-test-date for enabled calendar dates

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#881]
**Describe the bug**
The [code that generated the markup for the shift calendar](https://github.com/rubyforgood/circulate/blob/main/app/views/volunteer/shifts/_month_calendar.html.erb#L19-L20) adds a `data-test-date` attribute to all days. This is generally OK, but some days can appear twice if the are near the beginning or end of a month. In that case, they get rendered in a disabled state in one month and in an enable one in another.

This leads to [systems tests breaking](https://github.com/rubyforgood/circulate/runs/4347530232?check_suite_focus=true#check-step-12) with error messages like this one:

```
Error:
Volunteer::ShiftsTest#test_views_shift_calendar:
Capybara::Ambiguous: Ambiguous match, found 2 elements matching visible css ".calendar-date[data-test-date='2021-11-29']"
    test/system/volunteer/shifts_test.rb:49:in `within_day'
    test/system/volunteer/shifts_test.rb:29:in `block (2 levels) in <class:ShiftsTest>'
    test/system/volunteer/shifts_test.rb:10:in `block in <class:ShiftsTest>'
rails test test/system/volunteer/shifts_test.rb:7
```

I'm guessing this will only pop up when we get into the end or beginning of a month as well.

This issue will be resolved when all the the values of `data-test-date` on a page are unique.

**To Reproduce**
Run the system tests during last few days of a month.

**Expected behavior**
The system tests should always pass, regardless of how near to the end of a month the current day is.

**Comment by AlanGabbianelli** [comment]
🙋🏻‍♂️

**Comment by AlanGabbianelli** [comment]
> 🙋🏻‍♂️

And by that I mean I can work on this 😁

**Comment by jim** [comment]
@AlanGabbianelli I ended up fixing this today as it was the end of the month again and broken tests were interfering with CI.
