### ISSUE TITLE
When an item is overdue change tag to a red "overdue" instead of yellow "checked out"

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#888]
**What?**
When an item in the item inventory pages is overdue, we'd like it to be more obvious to folks browsing the inventory.

**Why?**
This will help members avoid putting items on hold that are overdue (and unlikely to return soon or possibly at all).

**Where?**
The pages in question are the [inventory page](https://app.chicagotoollibrary.org/items) and the [item detail page](https://app.chicagotoollibrary.org/items/2736).

The main logic involved in displaying this information lives in the [item_status_label](https://github.com/rubyforgood/circulate/blob/c6b194dcc51d3d3645a1a3b502c0519d1f8bb7fc/app/helpers/items_helper.rb#L166) method. We should be able to extend that method (or perhaps [`css_class_and_status_label`](https://github.com/rubyforgood/circulate/blob/c6b194dcc51d3d3645a1a3b502c0519d1f8bb7fc/app/helpers/items_helper.rb#L150) to accomplish this change.

It would also be great to delete the [`item_status_class`](https://github.com/rubyforgood/circulate/blob/c6b194dcc51d3d3645a1a3b502c0519d1f8bb7fc/app/helpers/items_helper.rb#L171) method since it is no longer used.

**Comment by jim** [comment]
The branch [here](https://github.com/rubyforgood/circulate/blob/c6b194dcc51d3d3645a1a3b502c0519d1f8bb7fc/app/helpers/items_helper.rb#L152) needs to be extended to check if the loan is overdue.

**Comment by fpsvogel** [comment]
I'll take this one 🙂
