### ISSUE TITLE
Item page shows schedule link for holds that aren't ready

### ISSUE THREAD

**Issue by pjsier** [rubyforgood/circulate#950]
**Describe the bug**

If you have a hold on the item page the "Schedule an appointment" link shows up even if you aren't first in line or eligible to pick the item up yet. It looks like this conditional needs to take that into account:

https://github.com/rubyforgood/circulate/blob/85fb5f5915ebcbcfa6a0f7b348c806fb32b84e51/app/views/items/place_hold_on/_item_already_with_a_hold.html.erb#L8-L10

Not sure this is fully a bug, but it's a bit confusing when the link shows up to a page where the option for the item is disabled.

**To Reproduce**
1. Create a hold on an item that only allows one user at a time with one user
2. Create a hold on the same item with another user
3. Go to the item page and you should see the "Schedule an appointment" link, but after clicking it be unable to actually schedule pickup

**Expected behavior**

I would expect the link not to show up if I can't schedule a pickup for the item

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Firefox
 
**Additional context**

I'm happy to put in a quick PR for this if it's helpful!

**Comment by jim** [comment]
I agree. We should be able to make this smarter and only show the button if something is ready for pickup.
