### ISSUE TITLE
Display previous holds in the admin

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#980]
**Is your feature request related to a problem? Please describe.**
There have been a few occasions where we needed to know who had an item on hold previously. One example is when an item is missing and we think that maybe it wasn't checked out to a member.

**Describe the solution you'd like**

I've been looking this information up in the console, but it would be better to have it live on a page. There is a page that shows the current holds on an item. We could add a grouped button to this page that toggles between current and historic holds.

**Comment by stephanieminn** [comment]
I am tackling this one!

**Comment by jim** [comment]
This was fixed by #1015
