### ISSUE TITLE
Show number of holds on an item next to item status

### ISSUE THREAD

**Issue by CTLvivek** [rubyforgood/circulate#984]
**Is your feature request related to a problem? Please describe.**
Yes, member demand for similar items does not spread out equally because there is no way for members to know which items have the shorter hold lists without actually placing the item(s) on hold. 

As a consequence, members will often place all items in a category (say upholstery cleaners or table saws) on hold. If someone didn't do that they'd be just as likely to enter a hold line that has 12 people as one that had 4.

**Describe the solution you'd like**
Show number of holds on an item next to the item status when listed in the inventory when viewing as a member
![image](https://user-images.githubusercontent.com/86161788/155012614-4bbba7f9-4e53-49f2-8e57-f5baef3ae01d.png)

Show number of holds on an item next to the item status on an individual item page when viewing as a member
![image](https://user-images.githubusercontent.com/86161788/155013746-60e2e797-56c6-416b-bfd2-247bba3f10eb.png)

Show number of holds in the text of the Holds tab in the librarian/admin view. i.e. "Holds" becomes "Holds - 19".  This is totally a nice-to-have and could be crude or left out completely. It saves one click for librarians anytime they need to check the hold list length but if the above two options are implemented then they'll have other easy options.
![image](https://user-images.githubusercontent.com/86161788/155013885-b00b17aa-653a-4f05-b6cd-69b2e6d139fe.png)

**Describe alternatives you've considered**
Multiple language options and locations shown in the first two images. Having the number of holds show up directly next to the item status (both in list view and individual item view) is probably the best solution, but it does limit what language could be used.

**Additional context**
This feature should ideally not show up next to items that are "Available" but it wouldn't be the worst thing if Available items just showed "Holds: 0" or something like that.

**Comment by jim** [comment]
Fixed by #1031
